/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.schoolmanagementsystem.ui;

import com.mycompany.schoolmanagementsystem.examsys.DAO.ClassroomDAO;
import com.mycompany.schoolmanagementsystem.examsys.DAO.CourseDAO;
import com.mycompany.schoolmanagementsystem.examsys.DAO.ExamDAO;
import com.mycompany.schoolmanagementsystem.examsys.DAO.InstructorDAO;
import com.mycompany.schoolmanagementsystem.examsys.Exam;
import com.mycompany.schoolmanagementsystem.management.Classroom;
import com.mycompany.schoolmanagementsystem.management.Course;
import com.mycompany.schoolmanagementsystem.management.Instructor;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AdminManageExam extends javax.swing.JPanel {

    private List<Course> courseList;       // store courses in memory
    private List<Instructor> teacherList;  // store instructors in memory
    private List<Classroom> classroomList;

    public AdminManageExam() {
        initComponents();
        loadTeachersAndCourses(); // loads the combo box and list
        loadClassrooms();
        loadExamsIntoTable();     // loads the exam table
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE EXAM");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel2.setText("course:");

        jLabel3.setText("Date:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Exam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Instructor:");

        jLabel5.setText("Classroom:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Exam name:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jButton2.setText("Cancel Exam");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addExam();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cancelExam();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainFrame.instance.setPage(MainFrame.instance.getAdminMainScreen());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cancelExam() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            // No row selected
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select an exam row in the table to cancel/delete!");
            return;
        }

        // The exam ID is presumably in column 0 (Exam ID)
        int examID = (int) jTable1.getValueAt(selectedRow, 0);

        // Confirm delete
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete Exam ID " + examID + "?",
                "Cancel Exam", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Delete from DB
            ExamDAO examDAO = new ExamDAO();
            boolean deleted = examDAO.delete(examID);
            if (deleted) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Exam canceled (deleted) successfully!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Failed to delete exam from database!");
            }
            // Refresh table
            loadExamsIntoTable();
        }
    }

    private void addExam() {
        try {
            // 1) Sınav tarihini (ör: "2025-01-31") al
            String dateStr = jTextField1.getText().trim();
            if (dateStr.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid date (yyyy-mm-dd).");
                return;
            }
            // java.sql.Date'e dönüştür
            java.sql.Date examDate = java.sql.Date.valueOf(dateStr);

            // 2) Comboboxtan sınıf (Classroom) seç
            int selectedClassroomIndex = jComboBox2.getSelectedIndex();
            if (selectedClassroomIndex < 0) {
                JOptionPane.showMessageDialog(this,
                        "Please select a valid classroom from the dropdown!");
                return;
            }
            // classroomList'in dolu olduğunu varsayıyoruz
            Classroom selectedClassroom = classroomList.get(selectedClassroomIndex);
            int classroomID = selectedClassroom.getClassroomID();

            // 3) Listedeki kursu seç
            int selectedIndex = jList1.getSelectedIndex();
            if (selectedIndex < 0) {
                JOptionPane.showMessageDialog(this,
                        "Please select a course from the list!");
                return;
            }
            // courseList'in daha önce doldurulmuş olması lazım
            Course selectedCourse = courseList.get(selectedIndex);

            // 4) Comboboxtan eğitmen seç
            int comboIndex = jComboBox1.getSelectedIndex();
            if (comboIndex < 0) {
                JOptionPane.showMessageDialog(this,
                        "Please select an instructor!");
                return;
            }
            // teacherList de daha önce doldurulmuş olmalı
            Instructor selectedInstructor = teacherList.get(comboIndex);

            // 5) Yeni Exam nesnesi oluştur
            Exam newExam = new Exam();
            // İsteğe bağlı bir textField'dan sınav adı alabilirsiniz
            String examName = jTextField2.getText().trim(); // Yeni textField eklendi
            if (examName.isEmpty()) {
                examName = "New Exam"; // Varsayılan sınav adı
            }
            newExam.setExamName(examName);
            newExam.setExamDate(examDate);
            newExam.setCourseID(selectedCourse.getCourseID());
            newExam.setInvigilatorID(selectedInstructor.getInstructorID());
            newExam.setClassroomID(classroomID);

            // 6) Veritabanına ekle
            ExamDAO examDAO = new ExamDAO();
            int generatedID = examDAO.create(newExam);
            if (generatedID > 0) {
                JOptionPane.showMessageDialog(this,
                        "Exam created successfully (ID=" + generatedID + ")");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to create exam!");
            }

            // 7) Tabloyu yenile
            loadExamsIntoTable();

        } catch (IllegalArgumentException ex) {
            // dateStr biçimi "yyyy-mm-dd" değilse .valueOf() hata verir
            JOptionPane.showMessageDialog(this,
                    "Invalid date format: " + ex.getMessage());
        }
    }

    private void loadTeachersAndCourses() {
        // 1) Load Teachers into the JComboBox
        InstructorDAO instructorDAO = new InstructorDAO();
        // Burada yerel değişken değil, sınıf değişkenine atıyoruz
        this.teacherList = instructorDAO.getAllTeachers();

        jComboBox1.removeAllItems();
        for (Instructor instructor : this.teacherList) {
            // instructor.toString() varsayılan olarak 
            // "com.mycompany...Instructor@1a2b3c" döndürüyor olabilir.
            // Daha anlamlı görünmesi için Instructor sınıfında toString() 
            // override edebilir ya da getName()+" "+getSurname() kullanabilirsiniz:
            jComboBox1.addItem(instructor.getName() + " " + instructor.getSurname());
        }
        if (!this.teacherList.isEmpty()) {
            jComboBox1.setSelectedIndex(0);
        }

        // 2) Load Courses into the JList
        CourseDAO courseDAO = new CourseDAO();
        // Sınıf alanına atama
        this.courseList = courseDAO.getAllCourses();

        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Course c : this.courseList) {
            listModel.addElement(c.getCourseID() + " - " + c.getCourseName());
        }
        jList1.setModel(listModel);
    }

    private void loadClassrooms() {
        // ClassroomDAO'yu kullanarak sınıfları veritabanından alıyoruz.
        ClassroomDAO classroomDAO = new ClassroomDAO();
        // Classroom listesini bir sınıf alanına atıyoruz.
        this.classroomList = classroomDAO.getAll();

        // 1) Classrooms'ı JComboBox'a yükleme
        jComboBox2.removeAllItems(); // Önceki öğeleri temizliyoruz
        for (Classroom classroom : this.classroomList) {
            // Classroom nesnesinin uygun bir şekilde temsil edilmesi için
            // toString() metodunu override edebilir veya aşağıdaki gibi bir
            // format kullanabilirsiniz:
            jComboBox2.addItem(classroom.getClassroomID() + " - " + classroom.getClassroomName());
        }
        if (!this.classroomList.isEmpty()) {
            jComboBox2.setSelectedIndex(0); // Varsayılan olarak ilk öğeyi seç
        }

    }

    private void loadExamsIntoTable() {
        // 1) Get all exams from DB
        ExamDAO examDAO = new ExamDAO();
        List<Exam> examList = examDAO.getAll();

        // 2) Define column names
        String[] columnNames = {"Exam ID", "Exam Name", "Exam Date", "Course ID", "Instructor ID", "Classroom ID"};

        // 3) Create a DefaultTableModel with those column names, 0 rows initially
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

        // 4) Add each exam as a row in the table
        for (Exam ex : examList) {
            Object[] rowData = {
                ex.getExamID(),
                ex.getExamName(),
                ex.getExamDate(), // java.sql.Date or java.util.Date
                ex.getCourseID(),
                ex.getInvigilatorID(),
                ex.getClassroomID()
            };
            tableModel.addRow(rowData);
        }

        // 5) Finally, set this model to jTable1
        jTable1.setModel(tableModel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
